apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: "helloworld"
          imagePullPolicy: Never
          env:
            - name: GraphQLEnv
              value: "docker"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 8000